version: '2.1'

services:
  orb-cli:
    build:
      context: ./circleci-cli
      dockerfile: Dockerfile
      args:
        HOST_USER_ID: ${ENV_USER_ID}
        HOST_GROUP_ID: ${ENV_GROUP_ID}
        CONTAINER_LANGUAGE: ${ENV_LANGUAGE}
        CONTAINER_TIMEZONE: ${ENV_TIMEZONE}
    image: common-orb-cli:1.0
    hostname: common-orb-cli
    container_name: common-orb-cli
    environment:
      HOST_PROJECT_ROOT: ${PROJECT_HOME}/${COMPOSE_PROJECT_NAME}
    networks:
      - common-orb-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ../:/home/sphere-master/project:rw

networks:
  common-orb-network:
